# code: language=ansible
---

run_msc_installs: true
configure_homebrew: true
run_brew_bundle: false
configure_omz: true
configure_finder: true
configure_terminal: true
configure_streamdeck: true
configure_files: true

zsh_custom: "~/.oh-my-zsh-custom"
zsh_theme: "dje"
zsh_plugins: "git git-prompt virtualenv"

msc_installs:
  - Cyberduck
  - GIMP
  - GitHubDesktop
  - GoogleDrive
  - GrandPerspective
  - Slack
  - TheUnarchiver
  - WindowsApp
  - Zoom.us

git_projects:
  - "https://github.com/deversmann/mac-dev-playbook"
  - "https://github.com/deversmann/homeinfra"
  - "https://github.com/deversmann/otp-gen"

...