# code: language=ansible
---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - name: Configure passwordless sudo.
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ ansible_user_id }}"
        create: true
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0640'
        validate: '/usr/sbin/visudo -cf %s'
      become: true
      tags: ['passwordless_sudo']

    - name: Managed Software Center installs.
      ansible.builtin.import_role:
        name: deversmann.msc
      when: run_msc_installs
      tags: ['msc']

    - ansible.builtin.import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: ['homebrew']

    - ansible.builtin.import_tasks: tasks/omz.yml
      when: configure_omz
      tags: ['omz']

...